
name: Deploy To prod

on:
  push:
    branches:
      - main   

jobs:
  deploy:
    name: Deploy via FTP
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, exif, pcntl, bcmath, gd, intl, pdo, mysql
          tools: composer

      - name: Install Dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Prepare Deploy Files
        run: |
          rm -rf storage  # Remove local storage to avoid accidental uploads
          mkdir -p ARCHIDATAmain  # Create ARCHIDATAmain folder
          shopt -s extglob
          mv !(public|ARCHIDATAmain) ARCHIDATAmain/  # Move all files except public/ into ARCHIDATAmain/
          echo "Moved Laravel files to ARCHIDATAmain/"

      - name: Upload ARCHIDATAmain Folder to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.1
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }} 
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./ARCHIDATAmain/
          server-dir: ${{ secrets.FTP_PATH }}/ARCHIDATAmain/
          exclude: |
            **/storage/** 
            **/.git**/
            **/node_modules/**
            **/vendor/**
            **/.env**
            **/.github/**
            **/tests/**
            **/README.md**
            **/package.json**
            **/webpack.mix.js**
          delete: true  

      - name: Upload Public Folder to Root
        uses: SamKirkland/FTP-Deploy-Action@v4.3.1
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }} 
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./public/
          server-dir: ${{ secrets.FTP_PUBLIC_PATH }}/
          exclude: |
            **/storage/** 
 
      # - name: Trigger Laravel Deployment
      #   run: curl -X GET "https://${{ secrets.SITE_URL }}/deploy?key=${{ secrets.DEPLOY_SECRET }}"
